#!/usr/bin/env bash
#Configures an Ubuntu server with the requirements
cp /etc/hosts ~/hosts.new
sed -i /localhost$/d ~/hosts.new
echo -e "127.0.0.2\tlocalhost" >> ~/hosts.new
sed -i /facebook.com$/d ~/hosts.new
echo -e "8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
